---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admsa
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    run: nginx
  strategy:
    resources: {}
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: image-registry.openshift-image-registry:5000/broken/nginx
        name: nginx
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx
---
